const get = (req,res) =>{
    res.send([
      {
        "Title" : " I-Phone 8 red",
        "ImageAsset" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQitudrwa8SAzTIYRLDa0Md99V9wIqq0SC50A&usqp=CAU",
        "CategoryName":"Iphone Red",
        "Price":"67,940",
        "PublishedDate" : " Jan 18 2022",
        "BlogContent" : " Apple has confirmed that the iPhone 8 (Product)Red Special Edition and the iPhone 8 Plus (Product)Red Special Edition will be available in India from May onwards, with prices starting Rs67,940. The specifications remain the same as the existing iPhone 8 and 8 Plus devices, and will be available in the 64GB and 256GB storage options. ",
      },
      {
        "Title" : "APPLE WATCH SPORT BAND",
        "ImageAsset" :"https://images.squarespace-cdn.com/content/v1/59d2bea58a02c78793a95114/1638365114457-UTH698Z0T7NTHPDZD2YQ/Sport+Band.jpeg?format=300w",
        "CategoryName":"Apple Watch",
        "Price":"$49.00",
        "PublishedDate" : " feb 18 2021",
        "BlogContent" : " Made from a custom high-performance fluoroelastomer, the Sport Band is durable and strong, yet surprisingly soft . The smooth, dense material drapes elegantly across your wrist and feels comfortable next to your skin ",
      },
      {
        "id" : 2,
        "Title" : "Iphone 14",
        "ImageAsset" : "https://cdn.mos.cms.futurecdn.net/Mwt64pGtzxTzxdhv5ySLFK-970-80.jpg.webp",
        "CategoryName":"iphone",
        "Price":"99900",
        "PublishedDate" : "Aug 8 2023",
        "BlogContent" : " Back in March, the analyst Ming-Chi Kuo revealed that while the iPhone 14 Pro will get the new A16 Bionic chip as per usual, the regular iPhone 14 models will stick with the same A15 processor used in the iPhone 13 and iPhone SE 3.  ",
      },
      {
        "id" : 3,
        "Title" : " IPHONE 13 (PRODUCT)RED ",
        "ImageAsset" :"https://images.squarespace-cdn.com/content/v1/59d2bea58a02c78793a95114/1638557435572-UYISRNGX323H0CMYA0XM/iPhone+13.png?format=300w",
        "CategoryName":"iphone",
        "Price":"71990",
        "PublishedDate" : " Aug 12 2021",
        "BlogContent" : " Your iPhone will arrive ready to go with your number and plan information. If you connect with a carrier later, once your new phone arrives, you can insert a physical SIM card or use eSIM from any carrier that provides service for iPhone.",
      },
      {
        "id" : 4,
        "Title" : "Iphone 12",
        "ImageAsset" :"https://www.re-thinkingthefuture.com/wp-content/uploads/2021/08/A4907-10-Upcoming-Apple-products-built-and-conceptual-Image-1.jpg",
        "CategoryName":"iphone",
        "Price":"49900",
        "PublishedDate" : "Aug 8 2021",
        "BlogContent" : " It is also expected to have an A15 chip, a faster 5G network, and better battery life. It has same size of Iphone 13. ",
      },
      {
        "Title" : " Apple Watch Series ^",
        "ImageAsset" :"https://www.gannett-cdn.com/-mm-/925c90cac2950828bbb61819371c14292ee6081b/c=0-0-792-446/local/-/media/2021/03/08/USATODAY/usatsports/apple-watch-series-6-4__1_.jpg?width=660&height=372&fit=crop&format=pjpg&auto=webp",
        "CategoryName":"Apple Watch",
        "Price":"$999.99",
        "PublishedDate" : " sept 9 2021",
        "BlogContent" : "The Apple Watch Series 6 has a OLED touchscreen that’s extremely easy to control, and the Digital Crown on the side of the watch allows you to summon Siri with a touch or scroll through various menus. It also requires daily charging, but it’s a small price to pay for such a comprehensive smartwatch.",
      },
      {
        "Title" : "14-inch MacBook Pro ",
        "ImageAsset" :"https://photos5.appleinsider.com/gallery/48754-95199-macbok-air-xl.jpg",
        "CategoryName":"Mac book",
        "Price":"89,000",
        "PublishedDate" : " Oct 29 2019",
        "BlogContent" : " That model offers the Touch Bar, which in a few years' time will be looked back on more fondly than it has now, and of course it has the new M2 processor. It just doesn't add anything else, and what it leaves out — connectivity, performance — means that the machines either side of it seem better value.",
      },
      {
        "Title" : "Air Pods Pro ",
        "ImageAsset" :"https://www.re-thinkingthefuture.com/wp-content/uploads/2021/08/A4907-10-Upcoming-Apple-products-built-and-conceptual-Image-2.jpg",
        "CategoryName":"Air pods",
        "Price":"$450",
        "fp":"5",
        "PublishedDate" : " Oct 29 2022",
        "BlogContent" : " The design of AirPods Pro is expected to eliminate a short stem that sticks out from the bottom, resulting in an even more rounded shape closer in design to competing for wireless earbuds from Samsung and Google.",
      },
      {
        "Title" : " AR Smart Glasses ",
        "ImageAsset" :"https://www.re-thinkingthefuture.com/wp-content/uploads/2021/08/A4907-10-Upcoming-Apple-products-built-and-conceptual-Image-4.jpg",
        "CategoryName":"Smart Glass",
        "Price":"$999.99",
        "fp":"4",
        "PublishedDate" : " Dec 15 2022",
        "BlogContent" : "  Apple is working on Augmented Reality Smart Glasses . These glasses are assumed to feature a dedicated display, a built-in processor, and an ‘rOS’ or ‘Reality Operating System’. It is said that its inputs will be via touch panels, voice activation, and head gesture. It is also expected to support applications ranging from texting to mapping.",
      },
      {
        "Title" : "Apple Cars ",
        "ImageAsset" :"https://images.hindustantimes.com/auto/img/2021/12/23/1600x900/apple_icar_youtube_1612505634970_1612505641070_1640233113322.jpg",
        "CategoryName":"Apple Car",
        "Price":"6,89,000",
        "fp":"3",
        "PublishedDate" : "2023",
        "BlogContent" : " Apple Cars are one of the most awaited upcoming products of apple. It said that with this launch, Apple would be revolutionizing the automobile sector too. Apple cars are expected to be fully autonomous vehicles, rather than just an autonomous car software offering. The launch is expected somewhere between 2023 to 2025.",
      },
      {
        "Title" : " Apple’s own lightning charging cable",
        "ImageAsset" :"https://www.gannett-cdn.com/-mm-/925c90cac2950828bbb61819371c14292ee6081b/c=0-0-792-446/local/-/media/2021/03/08/USATODAY/usatsports/Reviewed.com-RvEW-26886-apple-cable_Cropped.jpg?width=660&height=372&fit=crop&format=pjpg&auto=webp",
        "CategoryName":"Charger",
        "Price":"3400",
        "fp":"2",
        "PublishedDate" : "Aug 8 2009",
        "BlogContent" : " This might not be as exciting of a purchase as, say, a new iPhone, but if you own any Apple product, chances are you’re going to need at least one lightning cable, which are the standard for charging most of the brand’s electronics. When we tested the best lightning cables, we found that Apple’s own USB-C option is the best for fast charging ",
      },
      {
        "Title" : "Air tags",
        "ImageAsset" :"https://www.re-thinkingthefuture.com/wp-content/uploads/2021/08/A4907-10-Upcoming-Apple-products-built-and-conceptual-Image-8.jpg",
        "CategoryName":"tag",
        "Price":"5432",
        "fp":"1",
        "PublishedDate" : "Aug 8 2022",
        "BlogContent" : " As said the new Air Tags include 31 emojis that can be added to the stainless steel model for free and can be personalized with the name as well. It is expected to have a replaceable battery, and protection against water and dust too. They are said to have an integrated speaker. One can attach them to their gym bag, laptop bag, and anything that needs attention. ",
      },
      
    ])
}
module.exports.apiController = get;