const get = (req,res) =>{
    res.send([
      {
        "id" : 1,
        "Title" : " 35W Dual USB-C Port Power Adapter",
        "ImageAsset" :"https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MNWP3_GEO_EMEA?wid=532&hei=582&fmt=png-alpha&.v=1653576603172",
        "CategoryName":"charger",
        "Price":"5800",
        "PublishedDate" : " Jan 18 2022",
        "BlogContent" : " The 35W Dual USB‑C Port Power Adapter allows you to charge two devices at the same time, whether you’re at home, in the office or on the go. Apple recommends using it with MacBook Air. You can also use it with iPhone, iPad, Apple Watch and AirPods.Pair this power adapter with the World Travel Adapter Kit to charge in other regions around the world.",
      },
      {
        "id" : 2,
        "Title" : "USB-C Digital AV Multiport Adapter",
        "ImageAsset" :"https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MUF82?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1590526633000",
        "CategoryName":"adaptar",
        "Price":"6900",
        "PublishedDate" : " feb 18 2021",
        "BlogContent" : "The USB-C Digital AV Multiport Adapter lets you connect your USB-C–enabled Mac or iPad to an HDMI display, while also connecting a standard USB device and a USB-C charging cable.This adapter allows you to mirror your Mac or iPad display to your HDMI-enabled TV or display.",
      },
      {
        "id" : 3,
        "Title" : " USB-C Charge Cable (2m)^",
        "ImageAsset" :"https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MLL82?wid=532&hei=582&fmt=png-alpha&.v=1575503793499",
        "CategoryName":"cable",
        "Price":"1900",
        "PublishedDate" : " Aug 12 2021",
        "BlogContent" : "This 2-metre charge cable — with USB-C connectors on both ends — is ideal for charging, syncing and transferring data between USB-C devices. Pair the USB-C Charge Cable with a compatible USB-C power adapter to conveniently charge your devices from a power point and take advantage of fast-charging capabilities. USB-C Power Adapters sold separately.",
      },
      {
        "aid":"1",
        "Title" : "14-inch MacBook Pro ",
        "ImageAsset" :"https://photos5.appleinsider.com/gallery/48754-95199-macbok-air-xl.jpg",
        "CategoryName":"Mac book",
        "Price":"89000",
        "PublishedDate" : " Oct 29 2019",
        "BlogContent" : " That model offers the Touch Bar, which in a few years' time will be looked back on more fondly than it has now, and of course it has the new M2 processor. It just doesn't add anything else, and what it leaves out — connectivity, performance — means that the machines either side of it seem better value.",
      },
      {
        "aid":"2",
        "Title" : "Air Pods Pro ",
        "ImageAsset" :"https://www.re-thinkingthefuture.com/wp-content/uploads/2021/08/A4907-10-Upcoming-Apple-products-built-and-conceptual-Image-2.jpg",
        "CategoryName":"Air pods",
        "Price":"26300",
        "fp":"fp",
        "PublishedDate" : " Oct 29 2022",
        "BlogContent" : " The design of AirPods Pro is expected to eliminate a short stem that sticks out from the bottom, resulting in an even more rounded shape closer in design to competing for wireless earbuds from Samsung and Google.",
      },
      {
        "aid":"3",
        "Title" : " AIR Pods Max ",
        "ImageAsset" :"https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airpods-max-select-silver-202011?wid=470&hei=556&fmt=png-alpha&.v=1604021221000",
        "CategoryName":"Wireless Head Phones",
        "Price":"66100",
        "fp":"fp",
        "PublishedDate" : " Dec 15 2022",
        "BlogContent" : "  Accessing Dolby Atmos features requires Dolby Atmos–capable devices. Playback quality will depend on hardware, audio accessories and internet connection.",
      },
      {
        "aid":"4",
        "Title" : "Home Pod mini ",
        "ImageAsset" :"https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/homepod-mini-select-blue-202110_FV1?wid=934&hei=440&fmt=jpeg&qlt=95&.v=1633086025000",
        "CategoryName":"Home Pod mini",
        "Price":"8900",
        "fp":"fp",
        "PublishedDate" : "Jul 10 2022",
        "BlogContent" : "Control your smart home accessories with just your voice using HomePod mini.Privacy at home is essential. HomePod mini helps you keep your data private and secure.",
      },
      {
        "Title" : " Magic Mouse - Black Multi-Touch Surface",
        "ImageAsset" :"https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MMMQ3?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1645138486301",
        "CategoryName":"Mouse",
        "Price":"9500",
        "fp":"fp",
        "PublishedDate" : "Aug 8 2009",
        "BlogContent" : " Magic Mouse is wireless and rechargeable, with an optimised foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures such as swiping between web pages and scrolling through documents. ",
      },
      {
        "Title" : "Apple Studio Display",
        "ImageAsset" :"https://images.squarespace-cdn.com/content/v1/59d2bea58a02c78793a95114/1543643143870-8T34ERIHGZ11XEMWGI7O/Apple_10.5-iPad-Pro-Leather-Smart-Sleeve.png?format=300w",
        "CategoryName":"tv",
        "Price":"159900",
        "fp":"fp",
        "PublishedDate" : "Aug 8 2021",
        "BlogContent" : " Magic Mouse is wireless and rechargeable, with an optimised foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures such as swiping between web pages and scrolling through documents. ",
      },

    ])
}
module.exports.apiController = get;